plugins {
    id 'com.android.application'
}

android {
    namespace 'com.openai.pozvonimne'
    compileSdk 36

    defaultConfig {
        applicationId 'com.openai.pozvonimne'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '2.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

androidComponents {
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.signingConfig.enableV1Signing.set(true)
        variant.signingConfig.enableV2Signing.set(true)
        variant.signingConfig.enableV3Signing.set(true)
    }
}
